server:
  AppVersion: 1.0.0
  Port: :80
  Mode: Development
  ReadTimeout: 10
  WriteTimeout: 10
  SSL: false
  CtxDefaultTimeout: 12
  CSRF: false
  Debug: true

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: console
  Level: info